question_data = [{"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In &quot;Mario Kart 64&quot;, Waluigi is a playable character.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "TF2: The Medic will be credited for an assist if he heals a Spy that successfully saps a building.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "&quot;Mongolia&quot; was a part of the now non-existent U.S.S.R.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
                  "question": "DHCP stands for Dynamic Host Configuration Port.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Books", "type": "boolean", "difficulty": "hard",
                  "question": "Harry Potter was born on July 31st, 1980.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "Cats have whiskers under their legs.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "In &quot;Starbound&quot;, the track played by the Decorated Music Box is named &quot;Atlas&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
                  "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "A Facebook campaign placed Rage Against The Machine&#039;s &quot;Killing in the Name Of&quot; as the UK Christmas Number 1 in 2009.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
